### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by egbertpostma** [lausdahl/isoxmlviz#1]
When I run the tool I get the following response:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\egbert.postma\AppData\Roaming\Python\Python38\site-packages\isoxmlviz\__main__.py", line 1, in <module>
    from isoxmlviz import visualize
  File "C:\Users\egbert.postma\AppData\Roaming\Python\Python38\site-packages\isoxmlviz\visualize.py", line 14, in <module>
    from isoxmlviz.LineStringUtil import extract_lines_within, get_coordinates
  File "C:\Users\egbert.postma\AppData\Roaming\Python\Python38\site-packages\isoxmlviz\LineStringUtil.py", line 34, in <module>
    def get_coordinates(lines: list[LineString]):
TypeError: 'type' object is not subscriptable

I tried different taskdata sets, any clue?

**Comment by lausdahl** [comment]
any change you could share the input file with me so I can fix the issue
